--local oldUEL0001 = UEL0001
--UEL0001 = Class(oldUEL0001) {

--WarpInEffectThread = function(self, bones)
--        self:PlayUnitSound('CommanderArrival')
--        self:CreateProjectile('/effects/entities/UnitTeleport01/UnitTeleport01_proj.bp', 0, 1.35, 0, nil, nil, nil):SetCollision(false)
--        WaitSeconds(2.1)
--
--        local bp = self:GetBlueprint()
--        local psm = bp.Display.WarpInEffect.PhaseShieldMesh
--        if psm then
--            self:SetMesh(psm, true)
--        end
--
--        self:ShowBone(0, true)
--        self:SetUnSelectable(false)
--        self:SetBusy(false)
--        self:SetBlockCommandQueue(false)
--
--        for _, v in bones or bp.Display.WarpInEffect.HideBones do
--            self:HideBone(v, true)
--        end
--
--        local totalBones = self:GetBoneCount() - 1
--        for k, v in EffectTemplate.UnitTeleportSteam01 do
--            for bone = 1, totalBones do
--                CreateAttachedEmitter(self, bone, self.Army, v)
--            end
--        end

--        if psm then
--            WaitSeconds(6)
--            self:SetMesh(bp.Display.MeshBlueprint, true)
--        end
--    end,
--
--}
--
--TypeClass = UEL0001
--
--
--		like fuck i know what im doing here sad face 
--
--
--